swagger: "2.0"
info:
  title: Cine API
  version: "1.0"
produces:
  - application/json
consumes:
  - application/json

paths:
  /movies:
    get:
      tags: [movies]
      operationId: controllers.movies.showing_movies
      summary: Gets all of the showing movies
      responses:
        200:
          description: Returns schowing movies
          schema:
            type: array
            items: 
              $ref: '#/definitions/Movie'
        404:
          description: No movies

  /movies/all:
    get:
      tags: [movies]
      operationId: controllers.movies.all_movies
      summary: Gets all of the movies in the Database
      responses:
        200:
          description: Returns all movies
          schema:
            type: array
            items: 
              $ref: '#/definitions/Movie'
        404:
          description: No movies

  /screening/{screening_id}/room/{room_id}/seats:
    get:
      tags: [screenings]
      operationId: controllers.screenings.get_seats_REST
      summary: Gets all of the free Seats for a screening
      parameters:
        - $ref: '#/parameters/screening_id'
        - $ref: '#/parameters/room_id'
      responses:
        200:
          description: Returns all free Seats
          schema:
            type: array
            items: 
              $ref: '#/definitions/Seat'
        404:
          description: No movies
  
  /movie/{movie_id}:
    get:
      tags: [movies]
      operationId: controllers.movies.info_movie
      summary: Gets info for movie by id
      parameters:
        - $ref: '#/parameters/movie_id'
      responses:
        200:
          description: Returns info on Movie
          schema:
            items: 
              $ref: '#/definitions/Movie'
        404:
          description: No movie

  /movie/{movie_id}/screenings:
    get:
      tags: [screenings]
      operationId: controllers.screenings.screenings
      summary: Gets all screenings for a Movie (by Movie Id)
      parameters:
          - $ref: '#/parameters/movie_id'
      responses:
          200:
            description: Returns all screenings
            schema:
              type: array
              items: 
                $ref: '#/definitions/Screening'
          404:
            description: No Screenings

    post:
      tags: [movies]
      operationId: controllers.movies.add_movie_REST
      summary: Creates a new event
      parameters:
        - $ref: '#/parameters/calendar_id'
        - name: event_date
          in: body
          description: date of the event
          required: true
          schema:
            type: string
      responses:
        200:
          description: Successful response.
          schema:
            $ref: '#/definitions/Event'
        403:
          description: You are not allowed to add members to a calendar of which you are not a member
  
      
definitions:
  Movie:
    type: object
    properties:
      id:
        type: integer
        description: Unique ID of the Movie
        readOnly: true
      length_in_minutes:
        type: integer
        description: length of Movie in Minutes
        readOnly: true
      name:
        type: string
        description: Name of the Movie
        readOnly: true
      release_date:
        type: integer
        description: Year of release (fix it!)
        readOnly: true
  Screening:
    type: object
    properties:
      id:
        type: integer
        description: Unique ID of the Screening
        readOnly: true
      screening_time:
        type: string
        description: timing of screening (no timezones)
        readOnly: true
      room_id:
        type: integer
        description: Room of screening (FK)
        readOnly: true
      movie_id:
        type: integer
        description: id of the Movie (FK)
        readOnly: true
  Seat:
    type: object
    properties:
      id:
        type: integer
        description: Unique ID of the seat
        readOnly: true
      seat_number:
        type: string
        description: Number of the seat
        readOnly: true
      seat_row:
        type: integer
        description: Row of the seat
        readOnly: true
      room_id:
        type: integer
        description: id of the Room (FK)
        readOnly: true

parameters:
  movie_id:
    name: movie_id
    description: Movies's unique identifier
    in: path
    type: integer
    required: true
  screening_id:
    name: screening_id
    description: Screening's unique identifier
    in: path
    type: integer
    required: true
  room_id:
    name: room_id
    description: Room's unique identifier
    in: path
    type: integer
    required: true

