swagger: "2.0"
info:
  title: Cine API
  version: "1.0"
produces:
  - application/json
consumes:
  - application/json

paths:
  /movies:
    get:
      tags: [movies]
      operationId: controllers.movies.showing_movies
      summary: Gets all of the showing sovies
      responses:
        200:
          description: Returns schowing movies
          schema:
            type: array
            items: 
              $ref: '#/definitions/Movie'
        404:
          description: No movies
  
  /movie/{movie_id}:
    get:
      tags: [movies]
      operationId: controllers.movies.info_movie
      summary: Gets info for movie by id
      parameters:
        - $ref: '#/parameters/movie_id'
      responses:
        200:
          description: Returns info on Movie
          schema:
            items: 
              $ref: '#/definitions/Movie'
        404:
          description: No movie

  /movie/{movie_id}/screenings:
    get:
      tags: [screenings]
      operationId: controllers.screenings.screenings
      summary: Gets all screenings for a Movie (by Movie Id)
      parameters:
          - $ref: '#/parameters/movie_id'
      responses:
          200:
            description: Returns all screenings
            schema:
              type: array
              items: 
                $ref: '#/definitions/Screening'
          404:
            description: No Screenings
  
      
definitions:
  Movie:
    type: object
    properties:
      id:
        type: integer
        description: Unique ID of the Movie
        readOnly: true
      length_in_minutes:
        type: integer
        description: length of Movie in Minutes
        readOnly: true
      name:
        type: string
        description: Name of the Movie
        readOnly: true
      release_date:
        type: integer
        description: Year of release (fix it!)
        readOnly: true
  Screening:
    type: object
    properties:
      id:
        type: integer
        description: Unique ID of the Screening
        readOnly: true
      screening_time:
        type: string
        description: timing of screening (no timezones)
        readOnly: true
      room_id:
        type: integer
        description: Room of screening (FK)
        readOnly: true
      movie_id:
        type: integer
        description: id of the Movie (FK)
        readOnly: true

parameters:
  movie_id:
    name: movie_id
    description: Movies's unique identifier
    in: path
    type: integer
    required: true

